### ISSUE TITLE
Issue installing via URL in package manager

### ISSUE THREAD

**Issue by augustluhrs** [ababilinski/magic-leap-setup-tool#1]
Hello!

Was trying to follow the readme instructions for installing via package manager and ran into some errors:

`[Package Manager Window] Unable to add package [https://github.com/ababilinski/magic-leap-setup-tool.git]:
  [https://github.com/ababilinski/magic-leap-setup-tool.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository.`
  
  `[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/ababilinski/magic-leap-setup-tool.git]:
  [https://github.com/ababilinski/magic-leap-setup-tool.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository. [NotFound].`
  
  `[Package Manager Window] Error adding package: https://github.com/ababilinski/magic-leap-setup-tool.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)`

Might just be doing something wrong, but figured I may not be the only one with this issue in the future! Thanks

**Comment by augustluhrs** [comment]
Oh and installing via the releases page worked perfectly, just wanted to raise the issue about the package manager.

**Comment by ababilinski** [comment]
Thank you for catching this bug @augustluhrs 🙂. 

I just pushed [Release #0.2.2-beta](https://github.com/ababilinski/magic-leap-setup-tool/releases/tag/v0.2.2-beta). The update has the required manifest file.
